/**
 * Centralized utility for constructing public-facing frontend URLs.
 *
 * In production, uses `VITE_PUBLIC_APP_URL` env variable.
 * In the browser (dev or prod), falls back to `window.location.origin`.
 * In SSR / non-browser contexts, falls back to the env variable or empty string.
 *
 * IMPORTANT: This returns the FRONTEND origin, NOT the API origin.
 * - Frontend: https://app.ofc360.com  (or whatever the public domain is)
 * - API:      https://api.ofc360.com  (separate — do NOT use for public URLs)
 */

/**
 * Returns the public application origin (no trailing slash).
 *
 * Resolution order:
 *  1. `VITE_PUBLIC_APP_URL` environment variable
 *  2. `window.location.origin` (browser only)
 *  3. Empty string (SSR fallback — relative URLs still work)
 */
export function getPublicAppUrl(): string {
  // 1. Explicit env var takes priority (set in .env / .env.production / deployment config)
  const envUrl = (import.meta.env.VITE_PUBLIC_APP_URL as string | undefined)?.trim();
  if (envUrl) {
    return envUrl.replace(/\/+$/, "");
  }

  // 2. Browser context — use current origin ONLY IF it's a real public domain (not localhost / private IP)
  if (typeof window !== "undefined" && window.location?.origin) {
    const origin = window.location.origin;
    const isLocalhost = /^https?:\/\/(?:localhost|127\.0\.0\.1|0\.0\.0\.0)(?::\d+)?/i.test(origin);
    if (!isLocalhost) {
      return origin.replace(/\/+$/, "");
    }
  }

  // 3. Production fallback default (never localhost)
  return "https://app.ofc360.com";
}

// ─── Specific URL builders ──────────────────────────────────────────────────

/**
 * Generates the public Job Application URL for a given job.
 * @param jobId - The job ID or unique key
 * @returns Full URL like `https://app.ofc360.com/jobs/apply/abc123`
 */
export function getJobApplicationUrl(jobId: string): string {
  return `${getPublicAppUrl()}/jobs/apply/${jobId}`;
}

/**
 * Generates the public Career Site URL for a given slug.
 * @param slug - The career site slug
 * @returns Full URL like `https://app.ofc360.com/careers/acme-corp`
 */
export function getCareerSiteUrl(slug: string): string {
  return `${getPublicAppUrl()}/careers/${slug}`;
}

/**
 * Generates the employee onboarding invite URL.
 * @param token - The activation token
 * @returns Full URL like `https://app.ofc360.com/onboarding?token=xyz`
 */
export function getOnboardingUrl(token: string): string {
  return `${getPublicAppUrl()}/onboarding?token=${token}`;
}

/**
 * Generates a public job detail URL (for career site / board listings).
 * @param jobId - The job ID
 * @returns Full URL like `https://app.ofc360.com/jobs/abc123`
 */
export function getPublicJobUrl(jobId: string): string {
  return `${getPublicAppUrl()}/jobs/${jobId}`;
}

/**
 * Generates an employee referral portal URL for a specific job.
 * @param jobId - The job ID
 * @returns Full URL like `https://app.ofc360.com/referrals?job=abc123`
 */
export function getReferralUrl(jobId: string): string {
  return `${getPublicAppUrl()}/referrals?job=${jobId}`;
}

/**
 * Sanitizes a URL that may have been generated by the backend with localhost.
 * Replaces any localhost / 127.0.0.1 origin with the correct public app URL.
 *
 * This is used as a safety net for URLs returned by backend APIs that may
 * incorrectly use the server's local origin instead of the public frontend URL.
 */
export function sanitizePublicUrl(url: string): string {
  if (!url) return url;
  // Match http(s)://localhost:PORT or http(s)://127.0.0.1:PORT or http(s)://0.0.0.0:PORT
  const localhostPattern = /^https?:\/\/(?:localhost|127\.0\.0\.1|0\.0\.0\.0)(?::\d+)?/i;
  if (localhostPattern.test(url)) {
    return url.replace(localhostPattern, getPublicAppUrl());
  }
  return url;
}
