import { Table, TableBody, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { GlassCard } from "@/components/hrms/Shared";
import { Badge } from "@/components/ui/badge";
import { ValidationIssueRow } from "./issueTable/ValidationIssueRow";
import { EmptyValidationState, FilteredEmptyState } from "./issueTable/EmptyStates";
import { ValidationLoadingState, ValidationErrorState } from "./issueTable/ValidationLoadingError";
import { ValidationPagination } from "./issueTable/ValidationPagination";
import type { PayrollValidationIssue } from "@/services/payrollApi";

export interface ValidationIssueTableProps {
  paginatedIssues: PayrollValidationIssue[];
  totalPages: number;
  currentPage: number;
  pageSize: number;
  filteredIssuesCount: number;
  runId: string;
  loadingEmployees?: boolean;
  employeesError?: string | null;
  onPageChange: (page: number) => void;
  onViewIssue: (issue: PayrollValidationIssue) => void;
  onViewPayroll: (employeeId: string) => void;
  onRetry?: () => void;
  onReturnToPreview?: () => void;
  onClearFilters?: () => void;
}

export function ValidationIssueTable({
  paginatedIssues,
  totalPages,
  currentPage,
  pageSize,
  filteredIssuesCount,
  runId,
  loadingEmployees,
  employeesError,
  onPageChange,
  onViewIssue,
  onViewPayroll,
  onRetry,
  onReturnToPreview,
  onClearFilters,
}: ValidationIssueTableProps) {
  return (
    <GlassCard className="p-4 sm:p-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between border-b border-border pb-4">
        <div>
          <h3 className="font-display text-base font-semibold text-foreground">
            Employee Payroll Records
          </h3>
          <p className="text-xs text-muted-foreground">
            Individual computed payroll lines generated by the backend calculation engine.
          </p>
        </div>

        <Badge variant="outline" className="w-fit text-xs font-normal">
          Total Records:{" "}
          <strong className="ml-1 font-semibold">{filteredIssuesCount}</strong>
        </Badge>
      </div>

      <div className="mt-4 overflow-x-auto rounded-xl border border-border">
        <Table>
          <TableHeader>
            <TableRow className="bg-muted/40 text-xs">
              <TableHead className="w-24">Severity</TableHead>
              <TableHead>Employee</TableHead>
              <TableHead>Issue Description</TableHead>
              <TableHead>Category</TableHead>
              <TableHead>Component</TableHead>
              <TableHead>Blocking</TableHead>
              <TableHead className="text-right">Action</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {loadingEmployees ? (
              <ValidationLoadingState pageSize={pageSize} />
            ) : paginatedIssues.length > 0 ? (
              paginatedIssues.map((iss) => (
                <ValidationIssueRow
                  key={iss.id}
                  issue={iss}
                  runId={runId}
                  onViewIssue={onViewIssue}
                  onViewPayroll={onViewPayroll}
                />
              ))
            ) : employeesError ? (
              <ValidationErrorState error={employeesError} onRetry={onRetry} />
            ) : (
              <FilteredEmptyState onClearFilters={onClearFilters} />
            )}
          </TableBody>
        </Table>
      </div>

      <ValidationPagination
        currentPage={currentPage}
        totalPages={totalPages}
        filteredIssuesCount={filteredIssuesCount}
        onPageChange={onPageChange}
      />
    </GlassCard>
  );
}