import type { Candidate, Interview, Job, Offer } from "../types";

export const MOCK_JOBS: Job[] = [
  {
    id: "job-101",
    title: "Senior Full Stack Engineer",
    department: "Engineering",
    employmentType: "Full-time",
    experience: "5-8 yrs (Senior)",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "AWS"],
    salaryMin: 2200000,
    salaryMax: 3200000,
    currency: "INR",
    vacancies: 3,
    location: "Bengaluru, India (Hybrid)",
    workMode: "Hybrid",
    description: "Lead architecture and frontend/backend features for our enterprise AI automation platform. Design scalable distributed microservices and intuitive interactive UI.",
    responsibilities: [
      "Architect and ship production features in React 19 and Node/FastAPI services.",
      "Collaborate with AI researchers to deploy intelligent copilot agents.",
      "Mentor junior and mid-level software engineers on best practices.",
    ],
    requirements: [
      "5+ years building and scaling cloud-native web applications.",
      "Deep expertise in TypeScript, React, state management, and Node.js or Python.",
      "Solid understanding of relational databases and system design.",
    ],
    benefits: [
      "Competitive Salary + ESOPs",
      "Comprehensive Health & Wellness Coverage",
      "Annual Learning & Conference Stipend",
      "Flexible Remote/Hybrid Work Options",
    ],
    hiringManager: "Arun Verma (Director of Engineering)",
    recruiter: "Neha Kapoor (Lead Tech Recruiter)",
    status: "active",
    publishedAt: "2026-02-15T09:00:00Z",
    closingAt: "2026-04-15T18:00:00Z",
    applicants: 42,
  },
  {
    id: "job-102",
    title: "Staff AI/ML Engineer",
    department: "Data & AI Analytics",
    employmentType: "Full-time",
    experience: "8+ yrs (Lead / Principal)",
    skills: ["Python", "PyTorch", "LLMs", "LangChain", "Vector DBs", "Docker"],
    salaryMin: 3500000,
    salaryMax: 5000000,
    currency: "INR",
    vacancies: 2,
    location: "Remote",
    workMode: "Remote",
    description: "Own our generative AI workflows, agentic routing pipelines, and intelligent resume parsing systems. Fine-tune local and cloud foundation models for HR domain workflows.",
    responsibilities: [
      "Train, fine-tune, and evaluate retrieval-augmented generation (RAG) pipelines.",
      "Optimize inference latencies for real-time interview assessment.",
      "Ensure ethical AI, bias mitigation, and data privacy across screening models.",
    ],
    requirements: [
      "Demonstrated track record of shipping LLM-powered applications into production.",
      "Hands-on experience with embeddings, rerankers, and vector databases.",
      "Strong computer science fundamentals and distributed computing experience.",
    ],
    benefits: [
      "Top-of-market equity grant",
      "Home office setup reimbursement",
      "Access to premium GPU compute clusters",
    ],
    hiringManager: "Vikram Malhotra (VP of AI)",
    recruiter: "Neha Kapoor (Lead Tech Recruiter)",
    status: "active",
    publishedAt: "2026-02-20T10:30:00Z",
    closingAt: "2026-04-30T18:00:00Z",
    applicants: 28,
  },
  {
    id: "job-103",
    title: "Lead Product Designer (UI/UX)",
    department: "Design & Creative",
    employmentType: "Full-time",
    experience: "5-8 yrs (Senior)",
    skills: ["Figma", "Design Systems", "Prototyping", "User Research", "SaaS UX"],
    salaryMin: 2000000,
    salaryMax: 2800000,
    currency: "INR",
    vacancies: 1,
    location: "Hyderabad, India (Hybrid)",
    workMode: "Hybrid",
    description: "Design consumer-grade experiences for complex B2B enterprise HR automation workflows. Craft elegant design systems and high-converting candidate flows.",
    responsibilities: [
      "Drive user journey mapping, design sprints, and wireframes to high-fidelity mocks.",
      "Maintain and evolve our design token library and UI component specs.",
      "Work closely with product managers and engineers during sprint executions.",
    ],
    requirements: [
      "Portfolio demonstrating complex SaaS applications and polished micro-interactions.",
      "Proven mastery of Figma, auto-layout, interactive components, and usability testing.",
    ],
    benefits: [
      "Hardware of choice (MacBook Pro + 4K Display)",
      "Wellness & Fitness Allowance",
      "Quarterly Team Offsites",
    ],
    hiringManager: "Pooja Sharma (Head of Product Design)",
    recruiter: "Rohan Sen (HR Partner)",
    status: "active",
    publishedAt: "2026-03-01T11:00:00Z",
    closingAt: "2026-05-01T18:00:00Z",
    applicants: 35,
  },
  {
    id: "job-104",
    title: "DevOps & Cloud Infrastructure Lead",
    department: "Engineering",
    employmentType: "Full-time",
    experience: "5-8 yrs (Senior)",
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Monitoring", "Security"],
    salaryMin: 2500000,
    salaryMax: 3600000,
    currency: "INR",
    vacancies: 1,
    location: "Bengaluru, India (Hybrid)",
    workMode: "Hybrid",
    description: "Scale our multi-tenant cloud infrastructure, CI/CD pipelines, and zero-downtime deployment pipelines with Kubernetes and Terraform.",
    responsibilities: [
      "Manage EKS clusters, VPC networking, and high-availability database replication.",
      "Automate security audits, container vulnerability scans, and SOC-2 compliance controls.",
    ],
    requirements: [
      "Extensive experience running production workloads in AWS with Infrastructure as Code.",
      "Proficiency in Prometheus, Grafana, Datadog, and distributed log tracing.",
    ],
    benefits: ["Health Insurance", "Stock Options", "Flexible Hours"],
    hiringManager: "Arun Verma (Director of Engineering)",
    recruiter: "Neha Kapoor (Lead Tech Recruiter)",
    status: "active",
    publishedAt: "2026-03-05T08:00:00Z",
    closingAt: "2026-05-05T18:00:00Z",
    applicants: 19,
  },
  {
    id: "job-105",
    title: "Senior People Operations Partner",
    department: "Human Resources",
    employmentType: "Full-time",
    experience: "3-5 yrs (Mid-Level)",
    skills: ["HR Operations", "Onboarding", "Employee Relations", "Compliance", "Payroll Sync"],
    salaryMin: 1200000,
    salaryMax: 1700000,
    currency: "INR",
    vacancies: 2,
    location: "Bengaluru, India (Onsite)",
    workMode: "Onsite",
    description: "Lead end-to-end employee onboarding, compliance verification, and HR operations for our rapidly expanding workforce.",
    responsibilities: [
      "Drive preboarding workflows, day-one orientations, and 30-60-90 check-ins.",
      "Facilitate background checks, document collections, and payroll data handovers.",
    ],
    requirements: [
      "3+ years experience in HR operations, tech recruiting, or employee experience.",
      "Strong empathetic communication and problem-solving abilities.",
    ],
    benefits: ["Health insurance", "Annual bonus", "Gym membership"],
    hiringManager: "Meera Nair (VP People)",
    recruiter: "Self",
    status: "active",
    publishedAt: "2026-03-10T10:00:00Z",
    closingAt: "2026-05-10T18:00:00Z",
    applicants: 54,
  },
];

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "cand-201",
    name: "Siddharth Nambiar",
    email: "siddharth.nambiar@example.com",
    phone: "+91 98450 12345",
    location: "Bengaluru, India",
    jobId: "job-101",
    applicationId: "app-301",
    appliedPosition: "Senior Full Stack Engineer",
    stage: "technical",
    atsScore: 94,
    jobMatch: 92,
    source: "LinkedIn Recruiter",
    tags: ["Top Match", "Fast Responder", "Immediate Joiner"],
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Docker", "AWS"],
    yearsExperience: 6.5,
    currentCompany: "Razorpay",
    currentRole: "Senior Software Engineer",
    expectedSalary: 2800000,
    noticeDays: 30,
    resumeName: "Siddharth_Nambiar_Resume_2026.pdf",
    summary: "Full stack engineer with 6.5 years specializing in high-throughput React/TypeScript architectures and resilient Node.js microservices. Led the merchant payments dashboard rebuild.",
    experience: [
      {
        company: "Razorpay",
        role: "Senior Software Engineer",
        start: "2022-03",
        end: "Present",
        highlights: [
          "Re-architected core merchant analytics dashboard cutting page load by 42%.",
          "Implemented automated real-time reconciliation with Kafka and Redis.",
        ],
      },
      {
        company: "Swiggy",
        role: "Software Development Engineer II",
        start: "2019-07",
        end: "2022-02",
        highlights: [
          "Built customer-facing tracking workflows serving 10M+ daily active sessions.",
        ],
      },
    ],
    education: [
      {
        school: "National Institute of Technology Karnataka (NIT Surathkal)",
        degree: "B.Tech in Computer Science and Engineering",
        start: "2015",
        end: "2019",
      },
    ],
    projects: [
      {
        name: "OpenSource React DataGrid",
        description: "Virtual scrolling high-performance table component with 3k+ GitHub stars.",
        tech: ["TypeScript", "Canvas", "React"],
      },
    ],
    certifications: ["AWS Certified Solutions Architect Associate"],
    languages: ["English", "Hindi", "Malayalam"],
    feedback: [
      {
        interviewer: "Arun Verma",
        round: "Technical Round 1",
        rating: 5,
        notes: "Exceptional depth in React internals, event loop, and database index tuning. Strong culture fit.",
        date: "2026-03-12T14:30:00Z",
      },
    ],
    notes: [
      {
        id: "n-1",
        at: "2026-03-11T10:00:00Z",
        author: "Neha Kapoor",
        text: "Passed screening test with 96% score. Ready for technical round.",
      },
    ],
    documents: [
      { name: "Siddharth_Nambiar_Resume.pdf", type: "Resume" },
      { name: "Degree_Certificate.pdf", type: "Education" },
      { name: "Experience_Letter_Swiggy.pdf", type: "Experience" },
    ],
    timeline: [
      { id: "t-1", at: "2026-03-08T09:00:00Z", kind: "system", title: "Applied via LinkedIn Recruiter", actor: "System" },
      { id: "t-2", at: "2026-03-09T11:15:00Z", kind: "stage", title: "AI Screened with 94% ATS Match", actor: "AI Screening Agent" },
      { id: "t-3", at: "2026-03-12T15:00:00Z", kind: "interview", title: "Technical Round 1 Completed (Rating: 5/5)", actor: "Arun Verma" },
    ],
    appliedAt: "2026-03-08T09:00:00Z",
  },
  {
    id: "cand-202",
    name: "Priyanka Deshmukh",
    email: "priyanka.deshmukh@example.com",
    phone: "+91 97112 34567",
    location: "Pune, India (Relocating to BLR)",
    jobId: "job-102",
    applicationId: "app-302",
    appliedPosition: "Staff AI/ML Engineer",
    stage: "interview",
    atsScore: 97,
    jobMatch: 95,
    source: "Naukri Resdex",
    tags: ["LLM Expert", "Top Tier Candidate"],
    skills: ["Python", "PyTorch", "HuggingFace", "LangChain", "Vector DBs", "Kubeflow"],
    yearsExperience: 8.0,
    currentCompany: "Freshworks",
    currentRole: "Lead Machine Learning Engineer",
    expectedSalary: 4200000,
    noticeDays: 45,
    resumeName: "Priyanka_Deshmukh_AI_Resume.pdf",
    summary: "Staff AI Engineer with 8 years building LLM pipelines, prompt evaluation frameworks, and semantic retrieval systems. Published 3 papers in natural language processing.",
    experience: [
      {
        company: "Freshworks",
        role: "Lead Machine Learning Engineer",
        start: "2021-04",
        end: "Present",
        highlights: [
          "Developed customer support auto-resolution agent saving $2.4M annually.",
          "Deployed hybrid semantic retrieval infrastructure handling 5M requests/day.",
        ],
      },
    ],
    education: [
      {
        school: "IIT Bombay",
        degree: "M.Tech in Artificial Intelligence",
        start: "2016",
        end: "2018",
      },
    ],
    projects: [
      {
        name: "AgentEval Benchmark",
        description: "Evaluation suite for enterprise AI agents on multi-turn reasoning.",
        tech: ["Python", "OpenAI SDK", "FastAPI"],
      },
    ],
    certifications: ["Google Cloud Certified Professional Machine Learning Engineer"],
    languages: ["English", "Marathi", "Hindi"],
    feedback: [],
    notes: [],
    documents: [{ name: "Priyanka_Resume.pdf", type: "Resume" }],
    timeline: [
      { id: "t-21", at: "2026-03-02T10:00:00Z", kind: "system", title: "Application received", actor: "System" },
      { id: "t-22", at: "2026-03-03T14:00:00Z", kind: "stage", title: "Shortlisted for Staff AI Role", actor: "Vikram Malhotra" },
    ],
    appliedAt: "2026-03-02T10:00:00Z",
  },
  {
    id: "cand-203",
    name: "Aditya Roy",
    email: "aditya.roy@example.com",
    phone: "+91 99881 22334",
    location: "Hyderabad, India",
    jobId: "job-103",
    applicationId: "app-303",
    appliedPosition: "Lead Product Designer (UI/UX)",
    stage: "offer",
    atsScore: 91,
    jobMatch: 89,
    source: "Career Site",
    tags: ["Design Systems", "High Seniority"],
    skills: ["Figma", "Design Systems", "User Research", "Interaction Design", "Prototyping"],
    yearsExperience: 7.0,
    currentCompany: "Postman",
    currentRole: "Senior Product Designer",
    expectedSalary: 2600000,
    noticeDays: 15,
    resumeName: "Aditya_Roy_Portfolio.pdf",
    summary: "Product designer passionate about Developer Tools and complex SaaS workflows. Creator of widely-adopted enterprise design systems.",
    experience: [
      {
        company: "Postman",
        role: "Senior Product Designer",
        start: "2021-08",
        end: "Present",
        highlights: ["Led API client redesign used by 25M developers worldwide."],
      },
    ],
    education: [
      {
        school: "National Institute of Design (NID)",
        degree: "B.Des in Interaction Design",
        start: "2014",
        end: "2018",
      },
    ],
    projects: [],
    certifications: [],
    languages: ["English", "Bengali", "Hindi"],
    feedback: [
      {
        interviewer: "Pooja Sharma",
        round: "Design Presentation",
        rating: 5,
        notes: "Flawless portfolio and deep design systems mastery.",
        date: "2026-03-10T11:00:00Z",
      },
    ],
    notes: [],
    documents: [{ name: "Aditya_Design_Portfolio.pdf", type: "Resume" }],
    timeline: [
      { id: "t-31", at: "2026-03-01T12:00:00Z", kind: "system", title: "Applied via Website", actor: "System" },
      { id: "t-32", at: "2026-03-14T16:00:00Z", kind: "stage", title: "Offer Generated", actor: "Rohan Sen" },
    ],
    appliedAt: "2026-03-01T12:00:00Z",
  },
  {
    id: "cand-204",
    name: "Kavita Ranganathan",
    email: "kavita.ranganathan@example.com",
    phone: "+91 94440 98765",
    location: "Chennai, India",
    jobId: "job-104",
    applicationId: "app-304",
    appliedPosition: "DevOps & Cloud Infrastructure Lead",
    stage: "screening",
    atsScore: 88,
    jobMatch: 86,
    source: "Internal Referral",
    tags: ["Referred by Arun V", "Kubernetes Pro"],
    skills: ["Kubernetes", "AWS", "Terraform", "ArgoCD", "Python", "Prometheus"],
    yearsExperience: 6.0,
    currentCompany: "Zoho",
    currentRole: "Lead Cloud Infrastructure Engineer",
    expectedSalary: 3000000,
    noticeDays: 60,
    resumeName: "Kavita_Ranganathan_DevOps.pdf",
    summary: "Cloud and site reliability engineer with 6 years leading multi-region AWS deployments and Kubernetes clusters.",
    experience: [],
    education: [],
    projects: [],
    certifications: ["CKA - Certified Kubernetes Administrator"],
    languages: ["English", "Tamil"],
    feedback: [],
    notes: [],
    documents: [],
    timeline: [
      { id: "t-41", at: "2026-03-10T09:30:00Z", kind: "system", title: "Referred by Arun Verma", actor: "System" },
    ],
    appliedAt: "2026-03-10T09:30:00Z",
  },
  {
    id: "cand-205",
    name: "Meera Kulkarni",
    email: "meera.kulkarni@example.com",
    phone: "+91 98200 45678",
    location: "Bengaluru, India",
    jobId: "job-105",
    applicationId: "app-305",
    appliedPosition: "Senior People Operations Partner",
    stage: "hired",
    atsScore: 92,
    jobMatch: 94,
    source: "LinkedIn Recruiter",
    tags: ["Preboarding Complete", "Joining April 1st"],
    skills: ["HR Operations", "Onboarding", "Compliance", "HRMS Tools", "Employee Engagement"],
    yearsExperience: 4.5,
    currentCompany: "PhonePe",
    currentRole: "People Operations Specialist",
    expectedSalary: 1500000,
    noticeDays: 15,
    resumeName: "Meera_Kulkarni_HR.pdf",
    summary: "People operations partner known for creating delightful onboarding journeys and managing full lifecycle HR operations for high-growth tech companies.",
    experience: [],
    education: [],
    projects: [],
    certifications: ["SHRM-CP Certified"],
    languages: ["English", "Hindi", "Kannada"],
    feedback: [],
    notes: [],
    documents: [],
    timeline: [
      { id: "t-51", at: "2026-02-18T10:00:00Z", kind: "system", title: "Applied", actor: "System" },
      { id: "t-52", at: "2026-03-10T11:00:00Z", kind: "offer", title: "Offer Accepted", actor: "Candidate" },
    ],
    appliedAt: "2026-02-18T10:00:00Z",
  },
];

export const MOCK_INTERVIEWS: Interview[] = [
  {
    id: "iv-301",
    candidateId: "cand-201",
    candidateName: "Siddharth Nambiar",
    jobTitle: "Senior Full Stack Engineer",
    interviewer: "Arun Verma (Director of Engineering)",
    round: "System Design & Architecture",
    date: "2026-03-18T14:30:00Z",
    durationMins: 60,
    meetingLink: "https://meet.google.com/ofc-eng-iv1",
    status: "scheduled",
    notes: "Deep dive into real-time pub-sub architecture and caching strategies.",
  },
  {
    id: "iv-302",
    candidateId: "cand-202",
    candidateName: "Priyanka Deshmukh",
    jobTitle: "Staff AI/ML Engineer",
    interviewer: "Vikram Malhotra (VP AI)",
    round: "AI Domain Deep Dive",
    date: "2026-03-19T16:00:00Z",
    durationMins: 60,
    meetingLink: "https://meet.google.com/ofc-ai-staff",
    status: "scheduled",
    notes: "Evaluation of fine-tuning strategies, inference optimization, and agentic loops.",
  },
  {
    id: "iv-303",
    candidateId: "cand-203",
    candidateName: "Aditya Roy",
    jobTitle: "Lead Product Designer (UI/UX)",
    interviewer: "Pooja Sharma",
    round: "Portfolio & Culture Alignment",
    date: "2026-03-10T11:00:00Z",
    durationMins: 45,
    meetingLink: "https://meet.google.com/ofc-design-round",
    status: "completed",
    rating: 5,
    feedback: "Exceptional candidate. Clear communication, top-tier design sensibility, and strong understanding of product metrics.",
  },
];

export const MOCK_OFFERS: Offer[] = [
  {
    id: "off-401",
    applicationId: "app-303",
    candidateId: "cand-203",
    candidateName: "Aditya Roy",
    jobId: "job-103",
    jobTitle: "Lead Product Designer (UI/UX)",
    salary: 2600000,
    currency: "INR",
    joiningDate: "2026-04-01T09:30:00Z",
    benefits: [
      "Health Insurance (₹10 Lakh sum insured for family)",
      "₹2 Lakh Annual ESOP grant",
      "₹75,000 Home Office & Tech Equipment Allowance",
      "Unlimited Sick Leave & 24 Annual Paid Leaves",
    ],
    status: "sent",
    sentAt: "2026-03-14T16:00:00Z",
    approvals: [
      { stage: "Hiring Manager Sign-off", by: "Pooja Sharma", at: "2026-03-13T10:00:00Z", status: "approved" },
      { stage: "Finance & Comp Review", by: "Kunal Gupta (CFO)", at: "2026-03-14T11:30:00Z", status: "approved" },
      { stage: "People VP Final Approval", by: "Meera Nair (VP People)", at: "2026-03-14T15:00:00Z", status: "approved" },
    ],
  },
  {
    id: "off-402",
    applicationId: "app-305",
    candidateId: "cand-205",
    candidateName: "Meera Kulkarni",
    jobId: "job-105",
    jobTitle: "Senior People Operations Partner",
    salary: 1500000,
    currency: "INR",
    joiningDate: "2026-04-01T09:30:00Z",
    benefits: [
      "Comprehensive Health Insurance",
      "Annual Performance Bonus (up to 15%)",
      "Wellness & Fitness Allowance",
    ],
    status: "accepted",
    sentAt: "2026-03-08T10:00:00Z",
    respondedAt: "2026-03-10T11:00:00Z",
    approvals: [
      { stage: "Hiring Manager Sign-off", by: "Meera Nair", at: "2026-03-07T12:00:00Z", status: "approved" },
      { stage: "Finance Approval", by: "Kunal Gupta (CFO)", at: "2026-03-08T09:30:00Z", status: "approved" },
    ],
  },
];
