import {
  Briefcase,
  CalendarClock,
  FileSignature,
  FileText,
  Folder,
  MessageSquare,
  Settings,
  TrendingUp,
  UserPlus,
  Users,
  Workflow,
  Target,
  Globe,
  FileSearch,
  Video,
  Send,
  UserCheck,
  ShieldCheck,
  Coins,
  Compass,
  Laptop,
  GraduationCap,
  type LucideIcon,
} from "lucide-react";

export type RecruitmentModule = {
  id: string;
  title: string;
  description: string;
  icon: LucideIcon;
  to: string;
  color: string;
};

export const RECRUITMENT_MODULES_LIST: RecruitmentModule[] = [
  {
    id: "workforce-planning",
    title: "Workforce Planning",
    description: "Align headcount demands with company strategy, budget cap modeling, and requisition approvals.",
    icon: Target,
    to: "/dashboard/recruitment/workforce-planning",
    color: "from-blue-600/20 to-indigo-600/20 text-blue-400 border-blue-500/30",
  },
  {
    id: "sourcing",
    title: "Candidate Sourcing",
    description: "Multi-channel sourcing across LinkedIn, job boards, referrals, and personalized outreach sequences.",
    icon: Globe,
    to: "/dashboard/recruitment/sourcing",
    color: "from-sky-500/20 to-teal-500/20 text-sky-400 border-sky-500/30",
  },
  {
    id: "requisitions",
    title: "Requisitions",
    description: "Manage open headcount requests, budget allocations, and review pending approval workflows.",
    icon: FileSignature,
    to: "/dashboard/recruitment/requisitions",
    color: "from-purple-500/20 to-indigo-500/20 text-purple-400 border-purple-500/30",
  },
  {
    id: "jobs",
    title: "All Jobs",
    description: "Post, edit, and publish active career listings and track active application pipelines.",
    icon: Briefcase,
    to: "/dashboard/recruitment/jobs",
    color: "from-blue-500/20 to-sky-500/20 text-blue-400 border-blue-500/30",
  },
  {
    id: "candidates",
    title: "Candidates",
    description: "Track candidate profiles, stage progressions, screening scores, and BGV checks.",
    icon: Users,
    to: "/dashboard/recruitment/candidates",
    color: "from-indigo-500/20 to-violet-500/20 text-indigo-400 border-indigo-500/30",
  },
  {
    id: "ai-screening",
    title: "AI Resume Screening",
    description: "Dynamic criteria weighting, ATS scoring breakdown, and multi-candidate comparative intelligence.",
    icon: FileSearch,
    to: "/dashboard/recruitment/ai-screening",
    color: "from-violet-500/20 to-fuchsia-500/20 text-violet-400 border-violet-500/30",
  },
  {
    id: "interviews",
    title: "Interviews & Scheduling",
    description: "Coordinate scheduler calendars, assign panel members, and manage candidate scorecards.",
    icon: CalendarClock,
    to: "/dashboard/recruitment/interviews",
    color: "from-cyan-500/20 to-blue-500/20 text-cyan-400 border-cyan-500/30",
  },
  {
    id: "ai-interview",
    title: "AI Interview & Integrity",
    description: "Simulate candidate video interviews, real-time speech evaluation, fraud & integrity signals.",
    icon: Video,
    to: "/dashboard/recruitment/ai-interview",
    color: "from-amber-500/20 to-orange-500/20 text-amber-400 border-amber-500/30",
  },
  {
    id: "communication",
    title: "Candidate Communications",
    description: "Automated multi-channel messaging templates, WhatsApp/SMS/Email previews, and delivery logs.",
    icon: Send,
    to: "/dashboard/recruitment/communication",
    color: "from-emerald-500/20 to-teal-500/20 text-emerald-400 border-emerald-500/30",
  },
  {
    id: "hiring-manager",
    title: "Hiring Manager Hub",
    description: "Role-specific pipeline reviews, pending candidate approvals, schedule tracking, and feedback.",
    icon: UserCheck,
    to: "/dashboard/recruitment/hiring-manager",
    color: "from-indigo-500/20 to-blue-500/20 text-indigo-400 border-indigo-500/30",
  },
  {
    id: "verification",
    title: "Background Verification (BGV)",
    description: "Identity, education, criminal, and employment verification tracking with exception resolution.",
    icon: ShieldCheck,
    to: "/dashboard/recruitment/verification",
    color: "from-red-500/20 to-rose-500/20 text-red-400 border-red-500/30",
  },
  {
    id: "compensation",
    title: "Compensation & Offer Builder",
    description: "Salary benchmarking, interactive component modeling, executive approvals, and e-signatures.",
    icon: Coins,
    to: "/dashboard/recruitment/compensation",
    color: "from-yellow-500/20 to-amber-500/20 text-yellow-400 border-yellow-500/30",
  },
  {
    id: "offers",
    title: "Offers & Contracts",
    description: "Generate customized offer letters, manage salary models, and track accepts.",
    icon: FileText,
    to: "/dashboard/recruitment/offers",
    color: "from-green-500/20 to-emerald-500/20 text-green-400 border-green-500/30",
  },
  {
    id: "preboarding",
    title: "Preboarding Engagement",
    description: "Keep accepted joiners engaged before Day 1, document submission, buddy chats, and readiness tracker.",
    icon: Compass,
    to: "/dashboard/recruitment/preboarding",
    color: "from-teal-500/20 to-cyan-500/20 text-teal-400 border-teal-500/30",
  },
  {
    id: "employee-onboarding",
    title: "Enterprise Onboarding Hub",
    description: "Cross-functional task execution across HR, IT, Admin, and Finance with Day-1 launch metrics.",
    icon: Laptop,
    to: "/dashboard/recruitment/employee-onboarding",
    color: "from-purple-500/20 to-pink-500/20 text-purple-400 border-purple-500/30",
  },
  {
    id: "kt-probation",
    title: "Knowledge Transfer & Probation",
    description: "Structured KT curriculum checklists, mentor pairing, 30-60-90 review gates, and confirmation.",
    icon: GraduationCap,
    to: "/dashboard/recruitment/kt-probation",
    color: "from-blue-500/20 to-cyan-500/20 text-blue-400 border-blue-500/30",
  },

  {
    id: "onboarding",
    title: "Onboarding Checklists",
    description: "Prepare welcome checklists, verify candidate documentation, and assign onboarding buddies.",
    icon: UserPlus,
    to: "/dashboard/recruitment/onboarding",
    color: "from-emerald-500/20 to-teal-500/20 text-emerald-400 border-emerald-500/30",
  },
  {
    id: "crm",
    title: "Candidate CRM",
    description: "Nurture relationships with email templates, pipeline triggers, and updates.",
    icon: MessageSquare,
    to: "/dashboard/recruitment/crm",
    color: "from-orange-500/20 to-amber-500/20 text-orange-400 border-orange-500/30",
  },
  {
    id: "talent-pool",
    title: "Talent Pool",
    description: "Access secondary candidate profiles, skills inventories, and past applications repository.",
    icon: Folder,
    to: "/dashboard/recruitment/talent-pool",
    color: "from-red-500/20 to-pink-500/20 text-red-400 border-red-500/30",
  },
  {
    id: "analytics",
    title: "Recruitment Analytics",
    description: "Monitor hiring pipeline conversion statistics, recruitment cost sources, and KPIs.",
    icon: TrendingUp,
    to: "/dashboard/recruitment/analytics",
    color: "from-sky-500/20 to-cyan-500/20 text-sky-400 border-sky-500/30",
  },
  {
    id: "automation",
    title: "Automation & Workflows",
    description: "Design trigger rules to auto-generate letters, update stages, and notify managers.",
    icon: Workflow,
    to: "/dashboard/recruitment/automation",
    color: "from-rose-500/20 to-red-500/20 text-rose-400 border-rose-500/30",
  },
  {
    id: "settings",
    title: "Recruitment Settings",
    description: "Configure candidate pipeline columns, career pages, and feedback templates.",
    icon: Settings,
    to: "/dashboard/recruitment/templates",
    color: "from-amber-500/20 to-yellow-500/20 text-amber-400 border-amber-500/30",
  },
];
