import { ShieldAlert } from "lucide-react";
import {
  Alert,
  AlertDescription,
  AlertTitle,
} from "@/components/ui/alert";

export function ProvisionalValidationNotice() {
  return (
    <Alert className="border-amber-500/40 bg-amber-500/10 text-amber-900 dark:text-amber-200">
      <ShieldAlert className="h-4 w-4 text-amber-600 dark:text-amber-400" />
      <AlertTitle className="text-xs font-semibold tracking-wide uppercase">
        PROVISIONAL PAYROLL AUDIT — Validation & Issues
      </AlertTitle>
      <AlertDescription className="text-xs text-amber-800/90 dark:text-amber-300/90 mt-1">
        Validation issues are generated by the server-side payroll engine to highlight
        inconsistencies, missing statutory numbers, or calculation discrepancies. Reviewing these
        issues does not finalize payroll, generate final payslips, or initiate bank disbursement.
        Salary has <strong>NOT</strong> been paid.
      </AlertDescription>
    </Alert>
  );
}