import { ArrowUpDown, FileSpreadsheet, RefreshCw } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { GlassCard, Skeleton } from "@/components/hrms/Shared";
import { Table } from "@/components/ui/table";
import type { PayrollEmployeeTableProps } from "../../types/payrollPreview.types";
import { PayrollTableHeader } from "./PayrollTableHeader";
import { PayrollTableBody } from "./PayrollTableBody";
import { PayrollFilters } from "./PayrollFilters";
import { PayrollPagination } from "./PayrollPagination";

export function PayrollEmployeeTable({
  employees,
  totalEmployees,
  totalPages,
  currentPage,
  pageSize,
  loadingEmployees,
  employeesError,
  searchQuery,
  selectedDept,
  selectedValidation,
  sortBy,
  sortDir,
  availableDepartments,
  onSearchChange,
  onDeptChange,
  onValidationChange,
  onPageChange,
  onPageSizeChange,
  onSort,
  onViewDetail,
  onRetry,
}: PayrollEmployeeTableProps) {
  return (
    <GlassCard className="p-4 sm:p-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between border-b border-border pb-4">
        <div>
          <h3 className="font-display text-base font-semibold text-foreground">
            Employee Payroll Records
          </h3>
          <p className="text-xs text-muted-foreground">
            Individual computed payroll lines generated by the backend calculation engine.
          </p>
        </div>

        <Badge variant="outline" className="w-fit text-xs font-normal">
          Total Records:{" "}
          <strong className="ml-1 font-semibold">{totalEmployees}</strong>
        </Badge>
      </div>

      <PayrollFilters
        searchQuery={searchQuery}
        selectedDept={selectedDept}
        selectedValidation={selectedValidation}
        availableDepartments={availableDepartments}
        pageSize={pageSize}
        onSearchChange={onSearchChange}
        onDeptChange={onDeptChange}
        onValidationChange={onValidationChange}
        onPageSizeChange={onPageSizeChange}
        onClearSearch={() => onSearchChange("")}
      />

      <div className="mt-4 overflow-x-auto rounded-xl border border-border">
        <Table>
          <PayrollTableHeader onSort={onSort} />
          <PayrollTableBody
            employees={employees}
            loadingEmployees={loadingEmployees}
            employeesError={employeesError}
            searchQuery={searchQuery}
            selectedDept={selectedDept}
            selectedValidation={selectedValidation}
            pageSize={pageSize}
            onViewDetail={onViewDetail}
            onRetry={onRetry}
          />
        </Table>
      </div>

      <PayrollPagination
        currentPage={currentPage}
        totalPages={totalPages}
        totalEmployees={totalEmployees}
        pageSize={pageSize}
        loading={loadingEmployees}
        onPageChange={onPageChange}
      />
    </GlassCard>
  );
}