import React from "react";
import { LineChart as LineChartIcon, FileText, FileSpreadsheet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/common/EmptyState";

export function CeoReportsPage() {
  return (
    <div className="space-y-6 pb-12 text-left">
      <div className="relative overflow-hidden rounded-2xl border border-purple-500/30 bg-gradient-to-r from-slate-900 via-purple-950/60 to-slate-950 p-6 shadow-xl backdrop-blur-xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div className="space-y-1.5">
            <div className="flex items-center gap-2">
              <span className="grid h-8 w-8 place-items-center rounded-lg bg-purple-500/20 text-purple-300 border border-purple-500/30">
                <LineChartIcon className="h-4 w-4" />
              </span>
              <Badge className="bg-purple-500/20 text-purple-300 border border-purple-500/30 text-[11px] font-bold uppercase">
                Executive Reports & Exports
              </Badge>
            </div>
            <h1 className="font-display text-2xl font-bold tracking-tight text-white sm:text-3xl">
              Board Reports & Financial Statements
            </h1>
            <p className="text-xs text-purple-200/70 max-w-2xl">
              Downloadable executive board decks, financial statements, HR workforce audits, sales pipelines, and SOC2 compliance reports.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <Button
              size="sm"
              disabled
              title="Coming soon"
              className="bg-muted text-muted-foreground text-xs opacity-70 cursor-not-allowed"
            >
              <FileText className="mr-1.5 h-3.5 w-3.5" />
              Export PDF Deck
            </Button>
            <Button
              size="sm"
              variant="outline"
              disabled
              title="Coming soon"
              className="border-border text-muted-foreground text-xs opacity-70 cursor-not-allowed"
            >
              <FileSpreadsheet className="mr-1.5 h-3.5 w-3.5" />
              Export Excel
            </Button>
          </div>
        </div>
      </div>

      <EmptyState
        title="Data not available yet"
        description="No executive reports have been compiled yet. Reports will appear here once generated by the system."
      />
    </div>
  );
}

export default CeoReportsPage;
